export const weatherIconMap: Record<string, string> = {
  Sunny: "line-md:moon-filled-to-sunny-filled-transition",
  Clear: "ri:moon-clear-fill",
  "Partly cloudy": "meteocons:partly-cloudy-day-fill",
  Cloudy: "mingcute:sun-cloudy-fill",
  Overcast: "ion:cloudy-night-sharp",
  Mist: "solar:fog-bold",
  "Patchy rain possible": "wi:day-rain-wind",
  "Patchy snow possible": "mdi:weather-snowy-heavy",
  "Patchy sleet possible": "mdi:weather-snowy-rainy", //
  "Patchy freezing drizzle possible": "mdi:weather-snowy-rainy",
  "Thundery outbreaks possible": "mdi:weather-lightning",
  "Blowing snow": "mdi:weather-snowy-heavy",
  Blizzard: "mdi:weather-snowy-heavy",
  Fog: "mdi:weather-fog",
  "Freezing fog": "mdi:weather-fog",
  "Patchy light drizzle": "mdi:weather-rainy",
  "Light drizzle": "mdi:weather-rainy",
  "Freezing drizzle": "mdi:weather-snowy-rainy",
  "Heavy freezing drizzle": "mdi:weather-snowy-rainy",
  "Patchy light rain": "mdi:weather-partly-rainy",
  "Light rain": "mdi:weather-rainy",
  "Moderate rain at times": "mdi:weather-rainy",
  "Moderate rain": "mdi:weather-rainy",
  "Heavy rain at times": "mdi:weather-pouring",
  "Heavy rain": "mdi:weather-pouring",
  "Light freezing rain": "mdi:weather-snowy-rainy",
  "Moderate or heavy freezing rain": "mdi:weather-snowy-rainy",
  "Light sleet": "mdi:weather-snowy-rainy",
  "Moderate or heavy sleet": "mdi:weather-snowy-rainy",
  "Patchy light snow": "mdi:weather-snowy",
  "Light snow": "mdi:weather-snowy",
  "Patchy moderate snow": "mdi:weather-snowy-heavy",
  "Moderate snow": "mdi:weather-snowy-heavy",
  "Patchy heavy snow": "mdi:weather-snowy-heavy",
  "Heavy snow": "mdi:weather-snowy-heavy",
  "Ice pellets": "mdi:weather-hail",
  "Light rain shower": "mdi:weather-partly-rainy",
  "Moderate or heavy rain shower": "mdi:weather-pouring",
  "Torrential rain shower": "mdi:weather-pouring",
  "Light sleet showers": "mdi:weather-snowy-rainy",
  "Moderate or heavy sleet showers": "mdi:weather-snowy-rainy",
  "Light snow showers": "mdi:weather-snowy",
  "Moderate or heavy snow showers": "mdi:weather-snowy-heavy",
  "Light showers of ice pellets": "mdi:weather-hail",
  "Moderate or heavy showers of ice pellets": "mdi:weather-hail",
  "Patchy light rain with thunder": "mdi:weather-lightning-rainy",
  "Moderate or heavy rain with thunder": "mdi:weather-lightning-rainy",
  "Patchy light snow with thunder": "mdi:weather-lightning-snowy",
  "Moderate or heavy snow with thunder": "mdi:weather-lightning-snowy",
};
